apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iceberg-ui
  namespace: eider
spec:
  rules:
  - host: iceberg-ui.eider.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iceberg-ui
            port:
              number: 80
